"use client";

import Link from "next/link";
import { Bot } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface AgentBranchBannerProps {
  branchName: string;
  branchId: string;
  runId?: string;
  notesCreated?: number;
  toolCalls?: number;
}

/**
 * Informational banner shown on branch detail pages when the branch was
 * created by the Workspace Operator (i.e. branches whose name starts
 * with `agent/`). Communicates that the content was AI-generated and
 * links to the branch review page.
 *
 * This is distinct from `ActiveBranchBanner` which warns about editing
 * on a draft branch — this banner is purely attributional.
 */
export function AgentBranchBanner({
  branchName,
  branchId,
  runId,
  notesCreated,
  toolCalls,
}: AgentBranchBannerProps) {
  const isAgentBranch = branchName.startsWith("agent/");
  if (!isAgentBranch) return null;

  return (
    <div
      role="status"
      aria-label="Generated by Workspace Operator"
      className="flex flex-col gap-1 border-b border-primary/20 bg-primary/5 px-4 py-2 text-xs text-primary"
    >
      <div className="flex flex-wrap items-center gap-2">
        <Bot className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
        <span>
          Generated by{" "}
          <strong className="font-semibold">Workspace Operator</strong> on
          branch <strong className="font-semibold">{branchName}</strong>
        </span>
        {notesCreated != null && notesCreated > 0 && (
          <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
            {notesCreated} note{notesCreated !== 1 ? "s" : ""} drafted
          </Badge>
        )}
        {toolCalls != null && toolCalls > 0 && (
          <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
            {toolCalls} tool call{toolCalls !== 1 ? "s" : ""}
          </Badge>
        )}
        <Link
          href={`/app/branches/${branchId}`}
          className="ml-auto underline hover:text-primary/80"
        >
          Review changes
        </Link>
      </div>
    </div>
  );
}
