"use client";

import { useState, useTransition } from "react";
import { Bot, ArrowUpFromLine, X } from "lucide-react";
import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";
import { promoteGeneratedNoteAction } from "@/app/app/notes/[note_id]/actions";
import { useRouter } from "next/navigation";

/**
 * Generated note banner.
 *
 * Shown on the note page when note.is_generated is true. Identifies the note
 * as machine-generated and provides a single "Promote" action to convert it
 * into a standard user-managed note.
 *
 * After promotion:
 *   - is_generated becomes false (this component unmounts on next render)
 *   - origin_type remains 'generated_by_tool' (provenance preserved)
 *   - generated_by_connection_id preserved for attribution
 *   - A new note version is created with change_origin='promotion'
 *
 * Promotion is human-only. External connections cannot promote notes.
 */
interface GeneratedNoteBannerProps {
  noteId: string;
  connectionName: string | null;
}

export function GeneratedNoteBanner({
  noteId,
  connectionName,
}: GeneratedNoteBannerProps) {
  const router = useRouter();
  const [dismissed, setDismissed] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  if (dismissed) return null;

  function handlePromote() {
    setError(null);
    startTransition(async () => {
      const result = await promoteGeneratedNoteAction(noteId);
      if (result.success) {
        router.refresh();
      } else {
        setError(result.error ?? "Promotion failed");
        setConfirmOpen(false);
      }
    });
  }

  return (
    <div className="mx-4 mt-4 rounded-2xl border border-border/50 bg-muted/30 px-4 py-3 sm:mx-6 lg:mx-8">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-2.5 min-w-0">
          <Bot className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground/70" />
          <div className="min-w-0">
            <p className="text-sm text-foreground/80">
              This note was generated by{" "}
              {connectionName ? (
                <span className="font-medium">{connectionName}</span>
              ) : (
                "an external tool"
              )}
              .
            </p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Promote it to take ownership as a standard note. Provenance and history are preserved.
            </p>
          </div>
        </div>
        <button
          onClick={() => setDismissed(true)}
          className="shrink-0 rounded p-0.5 text-muted-foreground/50 hover:text-muted-foreground transition-fast"
          aria-label="Dismiss"
        >
          <X className="h-3.5 w-3.5" />
        </button>
      </div>

      {!confirmOpen ? (
        <div className="mt-3 flex items-center gap-2">
          <button
            onClick={() => setConfirmOpen(true)}
            className={cn(
              "flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-xs font-medium transition-fast",
              "border border-border/60 hover:border-foreground/20 hover:bg-background",
              "text-foreground/80"
            )}
          >
            <ArrowUpFromLine className="h-3.5 w-3.5" />
            Promote to standard note
          </button>
        </div>
      ) : (
        <div className="mt-3 rounded-2xl border border-border/50 bg-background px-3.5 py-3 flex flex-col gap-2">
          <p className="text-xs text-foreground/80">
            This will mark the note as user-managed. A new version will be recorded.
            All prior history and attribution remain unchanged.
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePromote}
              disabled={isPending}
              className={cn(
                "flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-xs font-medium transition-fast",
                "bg-primary text-primary-foreground hover:bg-primary/90",
                "disabled:cursor-not-allowed disabled:opacity-50"
              )}
            >
              {isPending ? (
                <Spinner size={12} />
              ) : (
                <ArrowUpFromLine className="h-3 w-3" />
              )}
              Confirm promotion
            </button>
            <button
              onClick={() => { setConfirmOpen(false); setError(null); }}
              disabled={isPending}
              className="rounded-md px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground transition-fast disabled:opacity-50"
            >
              Cancel
            </button>
          </div>
          {error && (
            <p className="text-xs text-destructive">{error}</p>
          )}
        </div>
      )}
    </div>
  );
}
