import { Cpu, Zap, Clock } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * MachineProvenancePanel
 *
 * Shows machine-generated provenance metadata for a file, skill, agent, or note.
 * Only rendered when the object has a machine-relevant origin.
 *
 * Displays:
 *   - Origin type: generated | imported
 *   - Connection name (if generated by an external connection)
 *   - Creation timestamp
 *   - Pending proposal count (if any proposals target this object)
 *
 * Design principles:
 *   - Only shown when there is real signal to convey
 *   - Calm and technical language
 *   - Encourages human review without being alarmist
 *   - Does not show generated badge for user_created objects
 */

type OriginType = "user_created" | "imported" | "generated";

interface MachineProvenancePanelProps {
  originType: OriginType;
  /** Name of the connection that generated the object. */
  generatedByConnectionName?: string | null;
  /** ISO timestamp of creation. */
  createdAt: string;
  /** Number of pending proposals targeting this object. */
  pendingProposalCount?: number;
  /** Object name for context. */
  objectName?: string;
  className?: string;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function MachineProvenancePanel({
  originType,
  generatedByConnectionName,
  createdAt,
  pendingProposalCount = 0,
  objectName,
  className,
}: MachineProvenancePanelProps) {
  // No panel for user-created objects with no pending proposals
  if (originType === "user_created" && pendingProposalCount === 0) return null;

  return (
    <div
      className={cn(
        "flex flex-col gap-2 rounded-lg border border-border/50 bg-card p-3",
        className
      )}
      role="region"
      aria-label="Machine provenance"
    >
      <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
        Provenance
      </p>

      <div className="flex flex-col gap-1.5">
        {/* Origin */}
        {originType === "generated" && (
          <div className="flex items-center gap-2 text-xs">
            <Cpu className="h-3.5 w-3.5 shrink-0 text-purple-500" aria-hidden="true" />
            <span className="text-muted-foreground">
              Generated{generatedByConnectionName ? ` by ${generatedByConnectionName}` : " by a connection"}
            </span>
          </div>
        )}

        {originType === "imported" && (
          <div className="flex items-center gap-2 text-xs">
            <Zap className="h-3.5 w-3.5 shrink-0 text-muted-foreground" aria-hidden="true" />
            <span className="text-muted-foreground">Imported</span>
          </div>
        )}

        {/* Creation date */}
        <div className="flex items-center gap-2 text-xs text-muted-foreground/70">
          <Clock className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
          <span>Created {formatDate(createdAt)}</span>
        </div>

        {/* Pending proposals */}
        {pendingProposalCount > 0 && (
          <div className="flex items-center gap-2 text-xs">
            <div className="h-2 w-2 rounded-full bg-amber-500 animate-pulse" aria-hidden="true" />
            <span className="text-amber-600 dark:text-amber-400">
              {pendingProposalCount} pending {pendingProposalCount === 1 ? "proposal" : "proposals"}
              {" "}awaiting review
            </span>
          </div>
        )}
      </div>
    </div>
  );
}
