import { type SupabaseClient } from "@supabase/supabase-js";

/**
 * Workspace Operator runs — durable record of every Operator invocation.
 *
 * The Workspace Operator (`workspace_operator_service.ts`) is fire-and-forget
 * from the Modal side; this table is the Next.js side's source of truth for
 * what runs were kicked off, what their state is, and what they produced.
 *
 * Status transitions (enforced at the application layer):
 *
 *   queued  ─plan request──▶  planning   ─plan returned──▶  awaiting_approval
 *           ─execute (full)─▶  executing
 *
 *   awaiting_approval ─approve──▶  executing
 *   executing         ─done────▶  completed | failed
 *   any state         ─cancel──▶  cancelled
 *
 * The `plan` jsonb stores the approved plan steps array; `result` stores
 * the OperatorResult payload (notes_created, tool_calls, error). We keep
 * the count columns (`tool_calls`, `notes_created`, `duration_ms`)
 * denormalized so list views can filter / sort without parsing jsonb.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type OperatorRunMode = "plan" | "execute" | "full";

export type OperatorRunStatus =
  | "queued"
  | "planning"
  | "awaiting_approval"
  | "executing"
  | "completed"
  | "failed"
  | "cancelled";

export interface WorkspaceOperatorRunRow {
  id: string;
  workspace_id: string;
  user_id: string;
  branch_id: string | null;
  prompt: string;
  mode: OperatorRunMode;
  status: OperatorRunStatus;
  plan: unknown | null;
  result: unknown | null;
  error: string | null;
  notes_created: string[];
  tool_calls: number;
  duration_ms: number | null;
  /** LLM input tokens consumed by this run (Phase 4). Defaults to 0. */
  input_tokens: number;
  /** LLM output tokens generated by this run (Phase 4). Defaults to 0. */
  output_tokens: number;
  /**
   * Portion of `input_tokens` OpenAI billed at the cached rate. Subset of
   * input_tokens, not a separate category. (Phase 4)
   */
  cached_input_tokens: number;
  /** Model id that actually served the run (e.g. "gpt-4.1-mini"). */
  model: string | null;
  /**
   * When non-null, the UI has requested cancellation. The Python operator
   * polls `/api/agent/operator/check_cancel` between phases and aborts when
   * this flips. (Wave 1 F)
   */
  cancellation_requested_at: string | null;
  /** Optional per-run input-token cap. NULL = unlimited. (Wave 1 F) */
  max_input_tokens: number | null;
  /** Optional per-run output-token cap. NULL = unlimited. (Wave 1 F) */
  max_output_tokens: number | null;
  created_at: string;
  updated_at: string;
}

export interface CreateOperatorRunInput {
  workspaceId: string;
  userId: string;
  branchId?: string | null;
  prompt: string;
  mode: OperatorRunMode;
  /** Optional model id (e.g. "gpt-4.1-mini"). Recorded on the row at create time. */
  model?: string | null;
  /** Optional per-run input-token cap. */
  maxInputTokens?: number | null;
  /** Optional per-run output-token cap. */
  maxOutputTokens?: number | null;
}

export interface UpdateOperatorRunPatch {
  status?: OperatorRunStatus;
  plan?: unknown;
  result?: unknown;
  error?: string | null;
  notesCreated?: string[];
  toolCalls?: number;
  durationMs?: number | null;
  branchId?: string | null;
  /** LLM input tokens consumed (Phase 4). */
  inputTokens?: number;
  /** LLM output tokens generated (Phase 4). */
  outputTokens?: number;
  /** Portion of inputTokens served from the OpenAI prompt cache (Phase 4). */
  cachedInputTokens?: number;
  /** Model id that served the run (Phase 4). */
  model?: string | null;
  /** ISO timestamp when cancellation was requested (Wave 1 F). */
  cancellationRequestedAt?: string | null;
  /** Per-run input-token cap (Wave 1 F). */
  maxInputTokens?: number | null;
  /** Per-run output-token cap (Wave 1 F). */
  maxOutputTokens?: number | null;
}

export interface ListOperatorRunsParams {
  /** Filter to a single workspace. Optional — omit to list across the user's workspaces. */
  workspaceId?: string;
  /** Filter to a single actor. Recommended for the "my runs" history view. */
  userId?: string;
  /** Page size. Defaults to 25, capped at 100. */
  limit?: number;
  /**
   * Opaque pagination cursor. The previous page's `nextCursor` is the
   * `created_at` ISO timestamp of the last row returned; pass it back to
   * continue the descending sort.
   */
  cursor?: string | null;
  /**
   * Optional status filter. Pass a single status or an array of statuses
   * to restrict the list (e.g. `["executing", "planning", "awaiting_approval"]`
   * for an "in-flight" filter). Filter composes with the other params via AND.
   */
  status?: OperatorRunStatus | OperatorRunStatus[];
  /**
   * Optional lower bound on `created_at`. ISO-8601 timestamp. Inclusive.
   * Composes with `cursor` — when both are set we apply both.
   */
  fromDate?: string;
  /**
   * Optional upper bound on `created_at`. ISO-8601 timestamp. Inclusive.
   */
  toDate?: string;
  /**
   * Optional case-insensitive substring match on the `prompt` column.
   * Wraps the caller's query in `%...%` so partial matches work. An
   * empty/whitespace string is treated as "no filter".
   */
  search?: string;
}

export interface ListOperatorRunsResult {
  rows: WorkspaceOperatorRunRow[];
  /** ISO timestamp of the last row's created_at, or null if no more pages. */
  nextCursor: string | null;
}

// ─── CRUD ─────────────────────────────────────────────────────────────────────

/**
 * Create a new run row. Status starts at 'queued'; callers advance it to
 * 'planning' / 'executing' before dispatch via {@link updateOperatorRun}.
 */
export async function createOperatorRun(
  supabase: SupabaseClient,
  input: CreateOperatorRunInput
): Promise<WorkspaceOperatorRunRow> {
  const prompt = input.prompt.trim();
  if (!prompt) throw new Error("Prompt is required");

  const insertPayload: Record<string, unknown> = {
    workspace_id: input.workspaceId,
    user_id: input.userId,
    branch_id: input.branchId ?? null,
    prompt,
    mode: input.mode,
    status: "queued",
  };
  if (input.model !== undefined) insertPayload.model = input.model;
  if (input.maxInputTokens !== undefined)
    insertPayload.max_input_tokens = input.maxInputTokens;
  if (input.maxOutputTokens !== undefined)
    insertPayload.max_output_tokens = input.maxOutputTokens;

  const { data, error } = await supabase
    .from("workspace_operator_runs")
    .insert(insertPayload)
    .select("*")
    .single();

  if (error || !data) {
    throw new Error(`Failed to create operator run: ${error?.message ?? "unknown"}`);
  }
  return data as WorkspaceOperatorRunRow;
}

/**
 * Apply a partial update to a run row.
 *
 * Only fields explicitly set in `patch` are written. We always bump
 * `updated_at` server-side via the trigger; we don't pass it from JS.
 */
export async function updateOperatorRun(
  supabase: SupabaseClient,
  runId: string,
  patch: UpdateOperatorRunPatch
): Promise<WorkspaceOperatorRunRow> {
  const update: Record<string, unknown> = {};
  if (patch.status !== undefined) update.status = patch.status;
  if (patch.plan !== undefined) update.plan = patch.plan;
  if (patch.result !== undefined) update.result = patch.result;
  if (patch.error !== undefined) update.error = patch.error;
  if (patch.notesCreated !== undefined) update.notes_created = patch.notesCreated;
  if (patch.toolCalls !== undefined) update.tool_calls = patch.toolCalls;
  if (patch.durationMs !== undefined) update.duration_ms = patch.durationMs;
  if (patch.branchId !== undefined) update.branch_id = patch.branchId;
  if (patch.inputTokens !== undefined) update.input_tokens = patch.inputTokens;
  if (patch.outputTokens !== undefined) update.output_tokens = patch.outputTokens;
  if (patch.cachedInputTokens !== undefined)
    update.cached_input_tokens = patch.cachedInputTokens;
  if (patch.model !== undefined) update.model = patch.model;
  if (patch.cancellationRequestedAt !== undefined)
    update.cancellation_requested_at = patch.cancellationRequestedAt;
  if (patch.maxInputTokens !== undefined)
    update.max_input_tokens = patch.maxInputTokens;
  if (patch.maxOutputTokens !== undefined)
    update.max_output_tokens = patch.maxOutputTokens;

  if (Object.keys(update).length === 0) {
    const existing = await getOperatorRun(supabase, runId);
    if (!existing) throw new Error("Operator run not found");
    return existing;
  }

  const { data, error } = await supabase
    .from("workspace_operator_runs")
    .update(update)
    .eq("id", runId)
    .select("*")
    .single();

  if (error || !data) {
    throw new Error(`Failed to update operator run: ${error?.message ?? "unknown"}`);
  }
  return data as WorkspaceOperatorRunRow;
}

/**
 * List runs with descending `created_at` ordering and cursor pagination.
 *
 * Pagination contract:
 *   - rows are ordered newest first
 *   - the cursor passed in is treated as "give me rows older than this"
 *   - the response's `nextCursor` is the oldest row's created_at, or null
 *     when fewer than `limit` rows came back (signalling end-of-stream)
 */
export async function listOperatorRuns(
  supabase: SupabaseClient,
  params: ListOperatorRunsParams = {}
): Promise<ListOperatorRunsResult> {
  const limit = Math.max(1, Math.min(params.limit ?? 25, 100));

  let query = supabase
    .from("workspace_operator_runs")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(limit);

  if (params.workspaceId) query = query.eq("workspace_id", params.workspaceId);
  if (params.userId) query = query.eq("user_id", params.userId);
  if (params.cursor) query = query.lt("created_at", params.cursor);

  // Optional filter composition — status, date range, prompt search all
  // AND together with the caller-supplied workspace/user/cursor filters.
  if (params.status !== undefined) {
    if (Array.isArray(params.status)) {
      if (params.status.length > 0) {
        query = query.in("status", params.status);
      }
    } else {
      query = query.eq("status", params.status);
    }
  }
  if (params.fromDate) query = query.gte("created_at", params.fromDate);
  if (params.toDate) query = query.lte("created_at", params.toDate);
  if (params.search) {
    const needle = params.search.trim();
    if (needle.length > 0) {
      // Escape the SQL LIKE wildcards so user input isn't interpreted as
      // a pattern. `ilike` is case-insensitive.
      const escaped = needle.replace(/[\\%_]/g, (m) => `\\${m}`);
      query = query.ilike("prompt", `%${escaped}%`);
    }
  }

  const { data, error } = await query;
  if (error) throw new Error(`Failed to list operator runs: ${error.message}`);
  const rows = (data ?? []) as WorkspaceOperatorRunRow[];

  const nextCursor =
    rows.length === limit ? (rows[rows.length - 1]?.created_at ?? null) : null;

  return { rows, nextCursor };
}

/**
 * Fetch a single run by id, or null when no row matches (or when RLS hides
 * it). Service-layer callers never need to distinguish "not found" from
 * "not visible".
 */
export async function getOperatorRun(
  supabase: SupabaseClient,
  runId: string
): Promise<WorkspaceOperatorRunRow | null> {
  const { data, error } = await supabase
    .from("workspace_operator_runs")
    .select("*")
    .eq("id", runId)
    .maybeSingle();

  if (error) throw new Error(`Failed to load operator run: ${error.message}`);
  return (data ?? null) as WorkspaceOperatorRunRow | null;
}
