-- =============================================================================
-- Context Store — export artifacts storage bucket
-- Migration: 20260409000010_export_artifacts_bucket.sql
--
-- Creates a private Supabase Storage bucket for export artifact delivery.
--
-- Design decisions:
--   - Private bucket: no public URLs ever issued.
--   - All access is via short-lived signed URLs generated by the service role.
--   - The bucket is used solely for ephemeral export packages (zip files).
--   - RLS is not meaningful here because all writes/reads go through the
--     service role client (which bypasses RLS). The private flag ensures
--     no accidental public access.
--
-- Storage path convention:
--   {workspaceId}/{unix-ms}-{filename}
--   e.g. 3f2a1b4c-.../1744000000000-my-box-box.zip
--
-- V1 cleanup strategy:
--   Artifacts accumulate in this bucket. Signed URLs expire (1 hour), making
--   artifacts inaccessible without a new URL. No automatic purge in V1.
--   Future: a scheduled job can delete paths older than a retention threshold
--   (e.g., 7 days) using the Supabase Storage management API.
--   The file size limit matches the import size limit (25 MB). Box exports of
--   large boxes may exceed this — the export service will surface an upload
--   error in that case.
-- =============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'exports',
  'exports',
  false,
  26214400,  -- 25 MB in bytes
  ARRAY['application/zip', 'application/octet-stream']
)
ON CONFLICT (id) DO NOTHING;
